backend:
  name: github
  repo: kaishin/redalemeden.com
  squash_merges: true

publish_mode: editorial_workflow
media_folder: static

collections:
  - name: widegamut
    label: Wide Gamut
    label_singular: Entry
    identifier_field: date
    slug: "{{path}}"
    description: Custom microblog setup.
    folder: content/microblog
    media_folder: assets
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title, required: false }
      - { name: excerpt, label: Excerpt, widget: text, required: false }
      - { name: body, label: Body, widget: markdown }
      - { name: draft, label: Draft, widget: boolean, default: false }
      - { name: tags, label: Tags, widget: list, required: false }
      - { name: path, label: Path, widget: path-widget }
